#include "_modular/code/datums/components/crafting/recipes_ru.dm"

#include "_modular/code/defines/defines_ru.dm"
#include "_modular/code/defines/obj_ru.dm"
#include "_modular/code/game_ru/objects/effects_ru.dm"
#include "_modular/code/game_ru/jobs_ru.dm"
#include "_modular/code/game_ru/shuttle_engines_ru.dm"

// Loadout
// #include "_modular/code/modules/client/preference_setup/loadout/loadout_ears.dm"
// #include "_modular/code/modules/client/preference_setup/loadout/loadout_eyes.dm"
// #include "_modular/code/modules/client/preference_setup/loadout/loadout_eyes_vr.dm"

// Clothing
#include "_modular/code/modules/clothing/ears/earrings.dm"
#include "_modular/code/modules/clothing/ears/ears.dm"
#include "_modular/code/modules/clothing/glasses/glasses_vr.dm"
#include "_modular/code/modules/clothing/glasses/glasses.dm"
#include "_modular/code/modules/clothing/glasses/hud_vr.dm"
#include "_modular/code/modules/clothing/glasses/hud.dm"

// Integrated Electronics
#include "_modular/code/modules/integrated_electronics/core/assemblies/clothing.dm"

// Mining
//#include "_modular\code\modules\mining\abandonedcrates.dm"
//#include "_modular\code\modules\mining\abandonedcrates_vr.dm"
//#include "_modular\code\modules\mining\alloys.dm"
//#include "_modular\code\modules\mining\alloys_vr.dm"
//#include "_modular\code\modules\mining\fulton.dm"
//#include "_modular\code\modules\mining\kinetic_crusher.dm"
//#include "_modular\code\modules\mining\mine_items.dm"
//#include "_modular\code\modules\mining\mine_items_vr.dm"
//#include "_modular\code\modules\mining\mine_outcrops.dm"
//#include "_modular\code\modules\mining\mine_turfs.dm"
//#include "_modular\code\modules\mining\mine_turfs_vr.dm"
//#include "_modular\code\modules\mining\mineral_effect.dm"
//#include "_modular\code\modules\mining\ore.dm"
//#include "_modular\code\modules\mining\ore_box.dm"
//#include "_modular\code\modules\mining\ore_datum.dm"
//#include "_modular\code\modules\mining\resonator_vr.dm"
//#include "_modular\code\modules\mining\shelter_atoms_vr.dm"
//#include "_modular\code\modules\mining\shelters_vr.dm"
#include "_modular\code\modules\mining\drilling\drill.dm"
#include "_modular\code\modules\mining\drilling\scanner.dm"
//#include "_modular\code\modules\mining\machinery\machine_input_output_plates.dm"
//#include "_modular\code\modules\mining\machinery\machine_processing.dm"
//#include "_modular\code\modules\mining\machinery\machine_stacking.dm"
//#include "_modular\code\modules\mining\machinery\machine_unloading.dm"
//#include "_modular\code\modules\mining\ore_redemption_machine\construction.dm"
//#include "_modular\code\modules\mining\ore_redemption_machine\equipment_vendor.dm"
//#include "_modular\code\modules\mining\ore_redemption_machine\mine_point_items.dm"
//#include "_modular\code\modules\mining\ore_redemption_machine\survey_vendor.dm"

// Mob localization
#include "_modular/code/modules/mob_ru/mob_ru.dm"

// Organs
#include "_modular/code/modules/organs/internal/augment_ru.dm"
#include "_modular/code/modules/organs/internal/internal_ru.dm"
#include "_modular/code/modules/organs/internal/robotic_ru.dm"
#include "_modular/code/modules/organs/organs_ru.dm"
#include "_modular/code/modules/organs/subtypes_ru.dm"


// #include "_modular/code/modules/mob/new_player/sprite_accessories.dm"
#include "_modular/code/modules/mob/new_player/sprite_accessories_ear.dm"
#include "_modular/code/modules/mob/new_player/sprite_accessories_ear_ch.dm"
#include "_modular/code/modules/mob/new_player/sprite_accessories_ear_vr.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_extra.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_extra_ch.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_extra_vr.dm"
#include "_modular/code/modules/mob/new_player/sprite_accessories_tail.dm"
#include "_modular/code/modules/mob/new_player/sprite_accessories_tail_ch.dm"
#include "_modular/code/modules/mob/new_player/sprite_accessories_tail_vr.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_taur.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_taur_vr.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_vr.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_wing.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_wing_large_vr.dm"
// #include "_modular/code/modules/mob/new_player/sprite_accessories_wing_vr.dm"
#include "_modular/code/modules/mob/new_player/sprite_accessories_yw.dm"